name: .NET Core + SonarQube - Code Analysis

on:
  push:
    branches:
      - main

jobs:
  #build-and-deploy:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.303'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release -p:Configuration=Release

      - name: Test
        run: dotnet test -c Release

      #- name: Publish
       # run: dotnet publish -c Release -o ./publish -p:Configuration=Release

     # - name: Upload artifact
     #   uses: actions/upload-artifact@v2
     #   with:
     #     name: publish
     #     path: ./publish/Users.App